### ISSUE TITLE
Import new data/files

### ISSUE THREAD

**Issue by klequis** [klequis/private-money-client#62]
## Case
1. User is at Home
2. Clicks Import
3. Clicks Choose Files
4. Selects one or more files from local disk
5. Clicks Upload
After selecting the file(s) the UI will be:

6. Specifies account for each file using drop downs
7. Clicks Import

- [ ] #63 Upload files UI
- [ ] #64 Upload files to server
- [ ] #65 Dedup upload/existing overlapping dates
- [ ] #66 Add new data to tx collection
- [ ] Run rules
- [ ] Redirect to TxTbl
